import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/About.module.css'

const About = () => {
  return (
    <div>
        <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={`${styles.heading} ${styles.font}`}>About</div>
    <Image src={"https://ca.slack-edge.com/T04ESBCHT4P-U04G4EF23AN-ac08f8f1ceec-512"} width={400} height={400} alt='myImage'/>
    </div>
  )
}

export default About